### PR TITLE
Adds support for "require-sri-for" value

### PR DESCRIPTION
**Pull request by MrMDavidson**
To use;
```
app.UseCsp(
  csp =>{
    csp.RequireSriFor
      .ForScripts()
      .ForStyles();
  }
);
```

This will generate the append the header value `require-sri-for script style` which means that included script and style tags must have subresource integrity attributes.

See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-sri-for

### CODE REVIEW

**Comment by juunas11** [comment]
Thanks for the PRs! I'll try to look at them as soon as I can 🙂

**Comment by MrMDavidson** [comment]
No worries!

Just a note: I'm not super happy with the name of this API; the underlying directive that's generated is singular ("script", "style") but I feel like they should be plural. However they should probably match the underlying attribute, so... Also, I just realised that "For" is doubled up (`RequireSriFor.ForScripts()`).I think `RequireSri.ForScripts()` would be more natural (compared to `RequireSriFor.Scripts()`) but isn't 100% inline with the underlying directive.

**Comment by juunas11** [comment]
I would prefer `RequireSri.ForScripts()`

**Comment by MrMDavidson** [comment]
Renamed the classes/methods to use the more natural `RequireSri.For[Scripts|Styles]()`. My local environment is all askew at the moment, so apologies if it's broken anything.

**Comment by juunas11** [comment]
Well, thanks again! :)

**Pull request merged**
